import type { Product, Category, Collection } from "./types"

export const categories: Category[] = [
  {
    id: "earrings",
    name: "Earrings",
    image: "/images/category-earrings.png",
    productCount: 245,
    description: "Elegant earrings for every occasion",
  },
  {
    id: "rings",
    name: "Rings",
    image: "/images/category-rings.png",
    productCount: 189,
    description: "Timeless rings that capture hearts",
  },
  {
    id: "necklaces",
    name: "Necklaces",
    image: "/images/category-necklaces.png",
    productCount: 156,
    description: "Stunning necklaces for graceful elegance",
  },
  {
    id: "bangles",
    name: "Bangles",
    image: "/images/category-bangles.png",
    productCount: 98,
    description: "Traditional bangles with modern appeal",
  },
  {
    id: "pendants",
    name: "Pendants",
    image: "/images/category-pendants.png",
    productCount: 134,
    description: "Delicate pendants for subtle beauty",
  },
  {
    id: "mangalsutra",
    name: "Mangalsutra",
    image: "/images/category-mangalsutra.png",
    productCount: 67,
    description: "Sacred symbols of eternal love",
  },
]

export const collections: Collection[] = [
  {
    id: "heritage",
    name: "Heritage Collection",
    description: "Timeless pieces inspired by royal traditions",
    image: "/images/product-kundan-necklace.png",
    productCount: 45,
  },
  {
    id: "contemporary",
    name: "Contemporary",
    description: "Modern designs for the contemporary woman",
    image: "/images/product-diamond-earrings.png",
    productCount: 78,
  },
  {
    id: "bridal",
    name: "Bridal Collection",
    description: "Exquisite pieces for your special day",
    image: "/images/product-temple-bangle.png",
    productCount: 56,
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Ethereal Temple Gold Bangle",
    price: 125750,
    originalPrice: 135000,
    image: "/images/product-temple-bangle.png",
    category: "bangles",
    material: "22K Gold",
    weight: "12.5g",
    karat: "22K",
    size: "2.6 inches",
    description:
      "An exquisite temple-inspired bangle featuring intricate traditional motifs, handcrafted by master artisans. This piece embodies the rich heritage of Indian jewelry making with contemporary comfort.",
    features: [
      "Handcrafted by master artisans with 25+ years experience",
      "Traditional temple motifs with modern comfort fit",
      "Premium 22K gold with BIS hallmark certification",
      "Adjustable sizing available upon request",
      "Lifetime warranty against manufacturing defects",
      "Complimentary annual cleaning and polishing",
    ],
    inStock: true,
    rating: 4.9,
    reviews: 127,
    sku: "LX-TB-001",
    collection: "heritage",
  },
  {
    id: "2",
    name: "Celestial Diamond Studs",
    price: 85299,
    originalPrice: 92000,
    image: "/images/product-diamond-earrings.png",
    category: "earrings",
    material: "18K White Gold & Diamond",
    weight: "2.8g",
    karat: "18K",
    description:
      "Brilliant cut diamonds set in lustrous 18K white gold, these studs capture and reflect light beautifully. Perfect for both everyday elegance and special occasions.",
    features: [
      "GIA certified natural diamonds (0.75 ct total)",
      "18K white gold setting with secure push-back closure",
      "Excellent cut grade for maximum brilliance",
      "Conflict-free diamonds with ethical sourcing",
      "Professional cleaning service included",
      "Certificate of authenticity provided",
    ],
    inStock: true,
    rating: 4.8,
    reviews: 203,
    sku: "LX-DE-002",
    collection: "contemporary",
  },
  {
    id: "3",
    name: "Royal Kundan Heritage Necklace",
    price: 285000,
    originalPrice: 315000,
    image: "/images/product-kundan-necklace.png",
    category: "necklaces",
    material: "22K Gold & Kundan",
    weight: "65.2g",
    karat: "22K",
    description:
      "A magnificent kundan necklace that epitomizes royal elegance. Each stone is carefully selected and set using traditional techniques passed down through generations.",
    features: [
      "Authentic Kundan stones sourced from Rajasthan",
      "Traditional Jadau setting technique",
      "Meenakari work on the reverse side",
      "Matching earrings available separately",
      "Presented in luxury wooden jewelry box",
      "Heritage collection certificate included",
    ],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    sku: "LX-KN-003",
    collection: "heritage",
  },
  {
    id: "4",
    name: "Eternal Solitaire Ring",
    price: 195999,
    originalPrice: 210000,
    image: "/images/product-solitaire-ring.png",
    category: "rings",
    material: "Platinum & Diamond",
    weight: "4.2g",
    karat: "Platinum 950",
    description:
      "A timeless solitaire featuring a brilliant cut diamond in a classic six-prong platinum setting. The epitome of elegance and sophistication for life's most precious moments.",
    features: [
      "1.2 carat brilliant cut diamond (D color, VVS1 clarity)",
      "Platinum 950 setting for durability and purity",
      "GIA certified with detailed grading report",
      "Custom sizing available at no extra cost",
      "Lifetime warranty and annual inspection",
      "Elegant presentation box with LED lighting",
    ],
    inStock: true,
    rating: 5.0,
    reviews: 156,
    sku: "LX-SR-004",
    collection: "bridal",
  },
  {
    id: "5",
    name: "Graceful Gold Chain",
    price: 45750,
    originalPrice: 48500,
    image: "/images/product-gold-chain.png",
    category: "necklaces",
    material: "18K Gold",
    weight: "8.5g",
    karat: "18K",
    description:
      "A delicate yet durable gold chain perfect for layering or wearing alone. The refined link design offers versatility and timeless appeal.",
    features: [
      "18K gold with superior durability",
      "Precision-crafted links for smooth drape",
      "Secure lobster clasp closure",
      'Available in 16", 18", and 20" lengths',
      "Hypoallergenic and tarnish-resistant",
      "Complimentary gift wrapping",
    ],
    inStock: true,
    rating: 4.7,
    reviews: 94,
    sku: "LX-GC-005",
    collection: "contemporary",
  },
  {
    id: "6",
    name: "Pearl Drop Elegance",
    price: 32500,
    originalPrice: 35000,
    image: "/images/product-pearl-earrings.png",
    category: "earrings",
    material: "14K Gold & Freshwater Pearls",
    weight: "3.2g",
    karat: "14K",
    description:
      "Lustrous freshwater pearls suspended from delicate gold settings. These earrings embody classic sophistication with a contemporary twist.",
    features: [
      "AAA grade freshwater pearls with high luster",
      "14K gold settings with secure ear wires",
      "Hand-selected pearls for perfect matching",
      "Comfortable for all-day wear",
      "Pearl care instructions included",
      "Elegant velvet jewelry pouch",
    ],
    inStock: true,
    rating: 4.6,
    reviews: 78,
    sku: "LX-PE-006",
    collection: "contemporary",
  },
  {
    id: "7",
    name: "Diamond Tennis Bracelet",
    price: 165000,
    originalPrice: 175000,
    image: "/images/product-tennis-bracelet.png",
    category: "bangles",
    material: "18K White Gold & Diamond",
    weight: "12.8g",
    karat: "18K",
    description:
      "A classic tennis bracelet featuring perfectly matched diamonds in a flexible setting. The ultimate symbol of refined luxury and timeless style.",
    features: [
      "2.5 carats total weight of round brilliant diamonds",
      "Uniform diamond sizing for consistent sparkle",
      "Flexible setting for comfortable wear",
      "Secure box clasp with safety latch",
      "Professional diamond grading certificate",
      "Lifetime setting warranty",
    ],
    inStock: true,
    rating: 4.8,
    reviews: 112,
    sku: "LX-TB-007",
    collection: "contemporary",
  },
  {
    id: "8",
    name: "Vintage Cocktail Ring",
    price: 78500,
    originalPrice: 85000,
    image: "/images/product-cocktail-ring.png",
    category: "rings",
    material: "18K Gold & Mixed Gemstones",
    weight: "6.8g",
    karat: "18K",
    description:
      "A statement cocktail ring featuring a stunning array of colored gemstones in an art deco-inspired setting. Perfect for making a bold fashion statement.",
    features: [
      "Center emerald surrounded by diamonds and sapphires",
      "Art deco-inspired vintage design",
      "18K yellow gold setting with milgrain details",
      "Natural gemstones with certification",
      "Custom sizing available",
      "Vintage-style presentation box",
    ],
    inStock: true,
    rating: 4.7,
    reviews: 65,
    sku: "LX-CR-008",
    collection: "heritage",
  },
]

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id)
}

export const getRelatedProducts = (productId: string, category: string): Product[] => {
  return products.filter((product) => product.id !== productId && product.category === category).slice(0, 4)
}

export const getProductsByCollection = (collectionId: string): Product[] => {
  return products.filter((product) => product.collection === collectionId)
}
